### ISSUE TITLE
help example

### ISSUE THREAD

**Issue by Majoburo** [tlittenberg/ldasoft#10]
The example in the help doesn't work:
./gb_mcmc --orbit ../config/OrbitConfig1.txt --verbose --inj ../data/sources/RXJ0806.dat

**Comment by tlittenberg** [comment]
@Majoburo better late than never.  FIxed with commit e84cc0fd8e2

**Comment by tlittenberg** [comment]
@Majoburo just kidding,  b8c53e931ad fixes it and something else that would make for disappointing results
