### ISSUE TITLE
Parameters not changing when when iterating with GBMCMC

### ISSUE THREAD

**Issue by GersbachKa** [tlittenberg/ldasoft#22]
Upon running the following command, the output of GBMCMC has two parameters (I believe they are phi and costheta) which do not change at all throughout the analysis. Additionally, there are two other parameters (I believe psi and phi0) that alternate roughly between two values and do not mix well. 

The command I used to create this:
~/ldasoft/master/bin/gb_mcmc --inj ~/ldasoft/gbmcmc/etc/sources/verification/ZTFJ1539.dat --known-source --no-rj --duration 31457280 --cheat --samples 32 --step 10000

![image](https://user-images.githubusercontent.com/39284048/89834921-955fc100-db18-11ea-92ce-8aa175814269.png)

I am not sure which version last worked, but one that I know works is this commit: f5ba624059e5f51db6467e1f74eb0029630857a1

**Comment by tlittenberg** [comment]
@GersbachKa I pushed a fix to master.

**Comment by tlittenberg** [comment]
The sky location parameters *shouldn't* change.  The code now holds the sky location of known sources fixed to the true values.  There was a bug that was causing the polarization and phase parameters to get stuck.

**Comment by tlittenberg** [comment]
Give it a whirl and let me know if things look OK, and then we'll close the issue if you are happy
