### ISSUE TITLE
output sky-location parameters inconsistent with inputs

### ISSUE THREAD

**Issue by hereiskaye** [tlittenberg/ldasoft#33]
Hi, I am interested in doing parameter estimation for LISA and came across your amazing package. I tried the test run and have some question regarding the order of input (and output) parameters "cos_colat" and "long". 

I used command:
`gb_mcmc --inj  somepath/ldasoft/gbmcmc/etc/sources/verification/AMCVn.dat --em-prior somepath/ldasoft/gbmcmc/etc/sources/verification/AMCVn_prior.dat  --known-source --no-rj --cheat --samples 128 --fix-freq` and then `bash example_gb_catalog.sh 1` to analyse the results. 

The sky location (cos-colat,long) appears in all of the files, but the definitions seem inconsistent.
The parameter file is:
`> cat AMCVn.dat`
`#f(Hz) | fdot(Hz/s) | costheta | phi(rad) | m1 (msun) | m2 (msun) | cosinc | d (kpc)`
`0.001944144722 0 0.6080 2.9737 0.68 0.125 0.7314 0.302`
But the parameter estimation result suggests the other way around:
`> cat catalog_1/LDC0019441447_params.dat`
`0.001944144722 -2.01116740697e-18 2.83244402359e-22 2.9737 0.608 0.713865768392 0.249565325314 0.272174439929`
According to the [documentation](https://github.com/tlittenberg/ldasoft/tree/master/gbmcmc), the data in catalog_N/LDCFFFFFFFFFF_params.dat are: 
`f | fdot | A | cos_colat | long | cos_inc | psi | phi`

By comparing the number, it seems that (spreadsheet refers to [link](https://docs.google.com/spreadsheets/d/1PfwgaPjOpcEz_8RIcf87doyhErnT0cYTYJ9b6fC0yfA/edit))

- cos(co-latitude)[_in spreadsheet_]=costheta[_in AMCVn.dat_]=0.6080=long[_in LDC*params.dat_]

- longitude[_in spreadsheet_]=phi(rad)[_in AMCVn.dat_]=2.9737=cos_colat[_in LDC*params.dat_]

**Comment by tlittenberg** [comment]
You are correct, the documentation is out of phase with the code.  The `cos_colat` and `long` columns for the output files are indeed switched. I will shortly update the documentation.
